spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cco_dev?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: cco_dev_user
    password: Radello
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
 #     javax:
  #      persistence:
   #       schema-generation:
    #        create-source: metadata
     #       scripts:
      #        action: create
       #       create-target: cco_database_create.sql