spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cco_prod?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: cco_prod_user
    password: Radello
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC